FROM ubuntu:18.04
#Setup libimobile device, usbmuxd and some tools 
RUN export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get -y install unzip  wget curl libimobiledevice-utils libimobiledevice6 usbmuxd cmake git build-essential python jq

RUN apt update && apt install -y ffmpeg

#Setup nvm and install latest appium
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
RUN export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \
     . "$NVM_DIR/nvm.sh" && nvm install 16.16.0 && \
    nvm alias default 16.16.0 && \
    npm config set user 0 && npm config set unsafe-perm true && npm install -g appium

#Grab GADS-docker-server from github and extract it in /usr/local/bin
RUN wget https://github.com/shamanec/GADS-docker-server/releases/latest/download/container-server.zip
RUN unzip container-server.zip -d /usr/local/bin

#Grab go-ios from github and extract it in /usr/local/bin
RUN wget https://github.com/danielpaulus/go-ios/releases/latest/download/go-ios-linux.zip
RUN unzip go-ios-linux.zip -d /usr/local/bin

#Copy scripts and WDA ipa to the image
COPY configs/nodeconfiggen.sh /opt/nodeconfiggen.sh
COPY configs/ios-sync.sh /
COPY apps/WebDriverAgent.ipa /opt
COPY configs/supervision.p12 /opt
ENTRYPOINT ["/bin/bash","-c","/ios-sync.sh"]